filetype: fubs

detect:
    filename: "\\.fut$"

rules:
    - statement: "\\$[0-9a-z_]+"

    - identifier: "\\@[0-9a-zA-Z_]+"

    - symbol.operator: "[-+*/=<>.:;,~&|^!?]"
    - symbol.brackets: "[(){}]|\\[|\\]"

    - type: "\\b(bool|i1|i4|i8|pointer|f4|array|blob|void|any|)\\b"

    - constant.number: "\\b[0-9a-fA-F]+\\b"

    - symbol.brackets: "[(){}]|\\[|\\]"

    - constant.string:
        start: "\""
        end: "\""
        skip: "\\\\."
        rules:
            - constant.specialChar: "\\\\([\"'abfnrtv\\\\]|[0-3]?[0-7]{1,2}|x[0-9A-Fa-f]{1,2}|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8})"

    - constant.string:
        start: "'"
        end: "'"
        skip: "\\\\."
        rules:
            - error: "..+"
            - constant.specialChar: "\\\\([\"'abfnrtv\\\\]|[0-3]?[0-7]{1,2}|x[0-9A-Fa-f]{1,2}|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8})"

    - comment:
        start: "//"
        end: "$"
        rules:
            - todo: "(TODO|XXX|FIXME):?"
