filetype: fubs

detect:
    filename: "\\.fut$"

rules:
    - constant.number: "\\b[0-9][0-9a-f]*\\b"

    - constant.number: "\\$B[0-9a-f]*"
    - constant.number: "\\$L[0-9a-f]*"

    - symbol.operator: "[-+*/=<>.:;,~&|^!?]"
    - symbol.brackets: "[(){}]|\\[|\\]"

    - type: "\\[?\\b(bool|i1|i2|i4|i8|f4|array|blob|void|any|none|opaque|object|word|layout)\\b\\]"
    - type: "\\#[.A-Za-z_/0-9]+" # Classes

    - statement: "\\$[a-z_0-9^]+"

    - symbol.brackets: "[(){}]|\\[|\\]"

#    - constant.string: "\"[^\"]*\""
#
#    - constant.string: "`[^\"]*`"

    - constant.string:
        start: "\""
        end: "\""
        skip: "\\\\."
        rules:
            - constant.specialChar: "\\\\."

    - constant.string:
        start: "`"
        end: "`"
        skip: "\\\\."
        rules:
            - constant.specialChar: "\\\\."

    - constant.number: "\\$C."

    - comment:
        start: "//"
        end: "$"
        rules:
            - todo: "(TODO|wtf):?"
